local voxelConfig = {
    darkDirt = {
        name = "darkDirt",
        color = 0x654321FF,
        emissive = 0,
        roughness = 14,
        metallic = 0,
    },
    dirt = {
        name = "dirt",
        color = 0x8B4513FF,
        emissive = 0,
        roughness = 13,
        metallic = 0,
    },
    lightDirt = {
        name = "lightDirt",
        color = 0xA0522DFF,
        emissive = 0,
        roughness = 12,
        metallic = 0,
    },
    darkRock = {
        name = "darkRock",
        color = 0x383533FF,
        emissive = 0,
        roughness = 13,
        metallic = 2,
    },
    rock = {
        name = "rock",
        color = 0x605752FF,
        emissive = 0,
        roughness = 12,
        metallic = 1,
    },
    lightRock = {
        name = "lightRock",
        color = 0x716B60FF,
        emissive = 0,
        roughness = 10,
        metallic = 0,
    },
    darkGrass = {
        name = "darkGrass",
        color = 0x6B8E23FF,
        emissive = 0,
        roughness = 13,
        metallic = 0,
    },
    grass = {
        name = "grass",
        color = 0x9ACD32FF,
        emissive = 0,
        roughness = 12,
        metallic = 0,
    },
    lightGrass = {
        name = "lightGrass",
        color = 0xBDB76BFF,
        emissive = 0,
        roughness = 11,
        metallic = 0,
    },
    sand = {
        name = "sand",
        color = 0xD4B368FF,
        emissive = 0,
        roughness = 11,
        metallic = 0,
    },
    lightSand = {
        name = "lightSand",
        color = 0xD4B388FF,
        emissive = 0,
        roughness = 9,
        metallic = 0,
    },
    water = {
        name = "water",
        color = 0x41A5FFFF,
        emissive = 0,
        roughness = 0,
        metallic = 1,
    },
    lava = {
        name = "lava",
        color = 0xEE1F00FF,
        emissive = 15,
        roughness = 8,
        metallic = 0,
    },
    ice = {
        name = "ice",
        color = 0xADD8E6FF,
        emissive = 0,
        roughness = 1,
        metallic = 1,
    },
    snow = {
        name = "snow",
        color = 0xFFFFFFFF,
        emissive = 0,
        roughness = 14,
        metallic = 0,
    },
}
return voxelConfig
